services:
  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    networks:
      - microservicios-network

  mysql:
    image: mysql:9.0
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: devsudb
      MYSQL_USER: test
      MYSQL_PASSWORD: test
    ports:
      - 3306:3306
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    networks:
      - microservicios-network

  cliente-personas:
    image: cliente-persona:latest
    ports:
      - 8080:8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/devsudb
      SPRING_DATASOURCE_USERNAME: test
      SPRING_DATASOURCE_PASSWORD: test
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: user
      SPRING_RABBITMQ_PASSWORD: password
    networks:
      - microservicios-network
    depends_on:
      mysql:
        condition: service_healthy

  cuenta-movimientos:
    image: cuenta-movimientos:latest
    ports:
      - 8081:8081
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/devsudb
      SPRING_DATASOURCE_USERNAME: test
      SPRING_DATASOURCE_PASSWORD: test
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: user
      SPRING_RABBITMQ_PASSWORD: password
      PROXY_CLIENTE_PERSONA_CLIENTE_URL: http://cliente-personas:8080/clientes
    networks:
      - microservicios-network
    depends_on:
      mysql:
        condition: service_healthy

networks:
  microservicios-network: