server.port: 8080
spring:
  output.ansi.enabled: ALWAYS
  application.name: cliente-persona
  datasource:
    url: jdbc:mysql://localhost:3306/devsu
    username: test
    password: test
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  h2:
    console:
      enabled: true
      path: /h2-console
