server.port: 8080
spring:
  output.ansi.enabled: ALWAYS
  application.name: cliente-persona
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/devsudb}
    username: ${SPRING_DATASOURCE_USERNAME:test}
    password: ${SPRING_DATASOURCE_PASSWORD:test}
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: always
      schema-locations: classpath:db/BaseDatos.sql
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
