server.port: 8888
spring:
  config.activate.on-profile: test
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:testdb
  sql:
    init:
      mode: always
      platform: h2
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none