server.port: 8081
spring:
  output.ansi.enabled: ALWAYS
  application.name: cuenta-movimientos
  datasource:
    url: jdbc:mysql://localhost:3306/devsu
    username: test
    password: test
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
      path: /h2-console

proxy:
  cliente-persona:
    cliente-url: http://localhost:8080/clientes