server.port: 8081
spring:
  output.ansi.enabled: ALWAYS
  application.name: cuenta-movimientos
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/devsudb}
    username: ${SPRING_DATASOURCE_USERNAME:test}
    password: ${SPRING_DATASOURCE_PASSWORD:test}
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: always
      schema-locations: classpath:db/BaseDatos.sql
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none

proxy:
  cliente-persona:
    cliente-url: ${PROXY_CLIENTE_PERSONA_CLIENTE_URL:http://localhost:8080/clientes}
