server.port: 8081
spring:
  output.ansi.enabled: ALWAYS
  application.name: cuenta-movimientos
  datasource:
    url: jdbc:mysql://localhost:3306/devsudb
    username: test
    password: test
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: always
      schema-locations: classpath:db/BaseDatos.sql
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none

proxy:
  cliente-persona:
    cliente-url: http://localhost:8080/clientes