server.port: 8889
spring:
  config.activate.on-profile: test
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:testdb
  sql:
    init:
      mode: never
      platform: h2
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  rabbitmq:
    enabled: false